# Spring
spring:
  thymeleaf:
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/ninja_course
    username: ninja
    password: ninja
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Security
